### ISSUE TITLE
Is jailing still a priority to be mocked up?

### ISSUE THREAD

**Issue by SeanMcOwen** [BlockScience/PocketMathSpec#176]
Looking to figure out with the Pocket team whether it should still be modeled or if it is low priority

**Comment by SeanMcOwen** [comment]
The above comment is needed for the simulation modeling aspects but not necessarily math spec aspects

**Comment by jshorish** [comment]
> Every N relays, probability of being jailed M, add in false positivity rate

Just curious @SeanMcOwen if this was decided as an aggregate jailing rate (i.e. a chance every N relays of the ecosystem), or a node-based rate (i.e. a chance every N relays of each node). Would expect jailing to be rare so maybe aggregate jailing (with a random selection of a node if jailing is to occur) makes more sense, unless PN has priors on how likely an individual node is jailed?
